services:
  postgres:
    image: postgres:latest
    container_name: postgres_smart_todolist
    environment:
      POSTGRES_USER: labber
      POSTGRES_PASSWORD: labber
      POSTGRES_DB: smart-todolist
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  init:
    build:
      context: .
      dockerfile: Dockerfile.init
    depends_on:
      - postgres
    environment:
      POSTGRES_USER: labber
      POSTGRES_PASSWORD: labber
      POSTGRES_DB: smart-todolist
    restart: "no"

  express-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express_smart_todolist
    ports:
      - "${APP_PORT}:8080"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: labber
      DB_PASSWORD: labber
      DB_NAME: smart-todolist
    volumes:
      - .:/usr/src/app
    command: npm start

volumes:
  postgres_data:
