FROM postgres:latest

# Copy SQL scripts into the container
COPY ./db/schema /docker-entrypoint-initdb.d/schema
COPY ./db/seeds /docker-entrypoint-initdb.d/seeds

# Use a script to wait for the database to start and then run the seed files
COPY ./init-db.sh /docker-entrypoint-initdb.d/

RUN chmod +x /docker-entrypoint-initdb.d/init-db.sh
