services:
  postgres:
    image: postgres:latest
    container_name: postgres_smart_todolist
    environment:
      POSTGRES_USER: labber
      POSTGRES_PASSWORD: labber
      POSTGRES_DB: smart-todolist
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
